### PR TITLE
impl portable pulp simd variants and make the other ones (that are still used) safe

### PR DESCRIPTION
**Pull request by sarah-quinones**
pretty much every benchmark is faster with the new impl, with the exception of the smallest size (n = 64)

### CODE REVIEW

**Comment by sarah-quinones** [comment]
well that doesn't look good

**Comment by sarah-quinones** [comment]
ok i solved the macos-13 issue on my side. i'll try to investigate the other one

**Comment by sarah-quinones** [comment]
okay, should be fixed this time

**Review by kemingy — APPROVED** [review]
Amazing PR!

I have some questions for the future maintenance:

Do the changes in `pulp.rs` file support ARM out-of-box?

If I want to support ARM in the future, do I only need to implement the 3 functions in the `simd.rs` file?

**Comment by sarah-quinones** [comment]
the new ones in pulp.rs do support arm64, as well as any arch pulp supports in the future (when new ones get stabilized)

**Pull request merged**
